# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/axel/proyectos/simulador-automata

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/axel/proyectos/simulador-automata

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/axel/proyectos/simulador-automata/CMakeFiles /home/axel/proyectos/simulador-automata//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/axel/proyectos/simulador-automata/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simulador_automata

# Build rule for target.
simulador_automata: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simulador_automata
.PHONY : simulador_automata

# fast build rule for target.
simulador_automata/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_automata.dir/build.make CMakeFiles/simulador_automata.dir/build
.PHONY : simulador_automata/fast

src/TAD_automata.o: src/TAD_automata.c.o
.PHONY : src/TAD_automata.o

# target to build an object file
src/TAD_automata.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_automata.dir/build.make CMakeFiles/simulador_automata.dir/src/TAD_automata.c.o
.PHONY : src/TAD_automata.c.o

src/TAD_automata.i: src/TAD_automata.c.i
.PHONY : src/TAD_automata.i

# target to preprocess a source file
src/TAD_automata.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_automata.dir/build.make CMakeFiles/simulador_automata.dir/src/TAD_automata.c.i
.PHONY : src/TAD_automata.c.i

src/TAD_automata.s: src/TAD_automata.c.s
.PHONY : src/TAD_automata.s

# target to generate assembly for a file
src/TAD_automata.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_automata.dir/build.make CMakeFiles/simulador_automata.dir/src/TAD_automata.c.s
.PHONY : src/TAD_automata.c.s

src/TAD_string.o: src/TAD_string.c.o
.PHONY : src/TAD_string.o

# target to build an object file
src/TAD_string.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_automata.dir/build.make CMakeFiles/simulador_automata.dir/src/TAD_string.c.o
.PHONY : src/TAD_string.c.o

src/TAD_string.i: src/TAD_string.c.i
.PHONY : src/TAD_string.i

# target to preprocess a source file
src/TAD_string.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_automata.dir/build.make CMakeFiles/simulador_automata.dir/src/TAD_string.c.i
.PHONY : src/TAD_string.c.i

src/TAD_string.s: src/TAD_string.c.s
.PHONY : src/TAD_string.s

# target to generate assembly for a file
src/TAD_string.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_automata.dir/build.make CMakeFiles/simulador_automata.dir/src/TAD_string.c.s
.PHONY : src/TAD_string.c.s

src/TAD_upla.o: src/TAD_upla.c.o
.PHONY : src/TAD_upla.o

# target to build an object file
src/TAD_upla.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_automata.dir/build.make CMakeFiles/simulador_automata.dir/src/TAD_upla.c.o
.PHONY : src/TAD_upla.c.o

src/TAD_upla.i: src/TAD_upla.c.i
.PHONY : src/TAD_upla.i

# target to preprocess a source file
src/TAD_upla.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_automata.dir/build.make CMakeFiles/simulador_automata.dir/src/TAD_upla.c.i
.PHONY : src/TAD_upla.c.i

src/TAD_upla.s: src/TAD_upla.c.s
.PHONY : src/TAD_upla.s

# target to generate assembly for a file
src/TAD_upla.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_automata.dir/build.make CMakeFiles/simulador_automata.dir/src/TAD_upla.c.s
.PHONY : src/TAD_upla.c.s

src/Tad_data.o: src/Tad_data.c.o
.PHONY : src/Tad_data.o

# target to build an object file
src/Tad_data.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_automata.dir/build.make CMakeFiles/simulador_automata.dir/src/Tad_data.c.o
.PHONY : src/Tad_data.c.o

src/Tad_data.i: src/Tad_data.c.i
.PHONY : src/Tad_data.i

# target to preprocess a source file
src/Tad_data.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_automata.dir/build.make CMakeFiles/simulador_automata.dir/src/Tad_data.c.i
.PHONY : src/Tad_data.c.i

src/Tad_data.s: src/Tad_data.c.s
.PHONY : src/Tad_data.s

# target to generate assembly for a file
src/Tad_data.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_automata.dir/build.make CMakeFiles/simulador_automata.dir/src/Tad_data.c.s
.PHONY : src/Tad_data.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_automata.dir/build.make CMakeFiles/simulador_automata.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_automata.dir/build.make CMakeFiles/simulador_automata.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_automata.dir/build.make CMakeFiles/simulador_automata.dir/src/main.c.s
.PHONY : src/main.c.s

src/test_string.o: src/test_string.c.o
.PHONY : src/test_string.o

# target to build an object file
src/test_string.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_automata.dir/build.make CMakeFiles/simulador_automata.dir/src/test_string.c.o
.PHONY : src/test_string.c.o

src/test_string.i: src/test_string.c.i
.PHONY : src/test_string.i

# target to preprocess a source file
src/test_string.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_automata.dir/build.make CMakeFiles/simulador_automata.dir/src/test_string.c.i
.PHONY : src/test_string.c.i

src/test_string.s: src/test_string.c.s
.PHONY : src/test_string.s

# target to generate assembly for a file
src/test_string.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_automata.dir/build.make CMakeFiles/simulador_automata.dir/src/test_string.c.s
.PHONY : src/test_string.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... simulador_automata"
	@echo "... src/TAD_automata.o"
	@echo "... src/TAD_automata.i"
	@echo "... src/TAD_automata.s"
	@echo "... src/TAD_string.o"
	@echo "... src/TAD_string.i"
	@echo "... src/TAD_string.s"
	@echo "... src/TAD_upla.o"
	@echo "... src/TAD_upla.i"
	@echo "... src/TAD_upla.s"
	@echo "... src/Tad_data.o"
	@echo "... src/Tad_data.i"
	@echo "... src/Tad_data.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/test_string.o"
	@echo "... src/test_string.i"
	@echo "... src/test_string.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

